In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print'Vector:\n', a

Vector:
[1 2 3 4]


In [3]:
b=np.array([1,2,3,4,5], dtype=float)
print 'V vector:\n', b

V vector:
[ 1.  2.  3.  4.  5.]


In [4]:
c=np.array([True, False, True], dtype=bool)
print 'Bool vector:\n', c

Bool vector:
[ True False  True]


In [5]:
print c

[ True False  True]


In [6]:
print c.dtype

bool


In [7]:
d=np.arange(start=10, stop=20, step=2) #last - No
print 'Vector 10-20:\n', d

Vector 10-20:
[10 12 14 16 18]


In [8]:
e=np.arange(start=0, stop=1, step=0.3, dtype=float)
print 'V vector:\n', e

V vector:
[ 0.   0.3  0.6  0.9]


In [9]:
print c.ndim

1


In [11]:
print d.shape

(5L,)


In [13]:
a=np.array([1,2,3])
b=np.array([6,5,4])
k=2

print 'vector a:', a
print 'vector b:', b
print 'digit k:', k

vector a: [1 2 3]
vector b: [6 5 4]
digit k: 2


In [14]:
print 'Sum a and b:\n', a+b

Sum a and b:
[7 7 7]


In [15]:
print 'razn a and b:\n', a-b

razn a and b:
[-5 -3 -1]


In [16]:
print 'coord mult a and b:\n', a*b

coord mult a and b:
[ 6 10 12]


In [17]:
print 'mult v to d:\n', a*k

mult v to d:
[2 4 6]


In [18]:
from numpy.linalg import norm

In [21]:
a=np.array([1,2,-4])
print 'Vector a:\n', a

Vector a:
[ 1  2 -4]


In [22]:
print 'l1 norm of a:\n', norm(a, ord=1)

l1 norm of a:
7.0


In [24]:
a=np.array([1,2,-33])
print 'L2 norm of a:\n', norm(a, ord=2)

L2 norm of a:
33.0756708171


In [27]:
a=np.array([1,2,-3])
b=np.array([-4,3,8])
print 'Vector a:', a
print 'Vector b:', b

Vector a: [ 1  2 -3]
Vector b: [-4  3  8]


In [29]:
print 'L1 Dist a and b:\n', norm(a-b, ord=1)

L1 Dist a and b:
17.0


In [30]:
print 'L2 Dist a and b:\n', norm(a-b, ord=2)

L2 Dist a and b:
12.124355653


In [31]:
from scipy.spatial.distance import cdist

In [35]:
a=np.array([6,3,-15])
b=np.array([-1,0,7])
print 'Vector a:', a
print 'razm a:', a.shape
print 'Vector b:', b
print 'razm b:', b.shape

Vector a: [  6   3 -15]
razm a: (3L,)
Vector b: [-1  0  7]
razm b: (3L,)


In [36]:
a=a.reshape((1,3))
b=b.reshape((1,3))
print 'Vector-row a:', a
print 'Its razm:', a.shape
print 'Vecor-row b:', b
print 'Its razm:', b.shape

Vector-row a: [[  6   3 -15]]
Its razm: (1L, 3L)
Vecor-row b: [[-1  0  7]]
Its razm: (1L, 3L)


In [37]:
print 'Man dist a and b:', cdist(a,b,metric='cityblock')

Man dist a and b: [[ 32.]]


In [40]:
d=np.array([3,0,8,9,-10])
print 'Vector d:', d
print 'Dim d:', d.shape

Vector d: [  3   0   8   9 -10]
Dim d: (5L,)


In [49]:
print 'vector d with newaxis - row:\n', d[np.newaxis, :]
print 'dim:', d[np.newaxis, :].shape
print 'vector d witn newaxis - column:\n', d[:, np.newaxis]
print 'dim:', d[:, np.newaxis].shape

 vector d with newaxis - row:
[[  3   0   8   9 -10]]
dim: (1L, 5L)
vector d witn newaxis - column:
[[  3]
 [  0]
 [  8]
 [  9]
 [-10]]
dim: (5L, 1L)


In [51]:
a=np.array([6,3,-55])
b=np.array([-1,0,7])
print 'Euclid dist between a and b:', cdist(a[np.newaxis, :], b[np.newaxis, :], metric='euclidean')

Euclid dist between a and b: [[ 62.46599075]]


In [52]:
a=np.array([0,5,-1])
b=np.array([-4,9,3])
print a
print b

[ 0  5 -1]
[-4  9  3]


In [53]:
print 'Scal mult:', np.dot(a,b)

Scal mult: 42


In [54]:
print'Scal mult by method:', a.dot(b)

Scal mult by method: 42


In [58]:
cos_angle=np.dot(a, b)/norm(a)/norm(b)
print 'Cos:', cos_angle
print 'angle:', np.arccos(cos_angle)

Cos: 0.800036283647
angle: 0.643440633609
